In [1]:
import numpy as np

print("✅ NumPy imported successfully! Version:", np.__version__)

✅ NumPy imported successfully! Version: 2.4.1


---
<a id='1'></a>
## 1️⃣ Why NumPy? — List vs Array

| Feature | Python List | NumPy Array |
|---|---|---|
| Data types | Mixed (int, str, float) | **Same type only** |
| Speed | Slower | **Much faster** |
| Memory | More | **Less** |
| Multi-dimensions | Nested lists (messy) | **True nD support** |
| Math operations | Manual loops needed | **Built-in, vectorized** |

**Key Rule:** When NumPy converts a mixed-type list to an array, it **upcasts** everything to the most general type.

In [2]:
# Python lists allow mixed types
list_mixed  = [1, 2, "Denver"]   # int + string → list stores as-is
list_nums   = [1, 2, 3.1]        # int + float  → list stores as-is

# When converted to NumPy arrays, types are UNIFIED (upcasting)
arr_mixed = np.array(list_mixed)  # int + str  → all become string (unicode)
arr_nums  = np.array(list_nums)   # int + float → all become float64

print(f"  list_mixed  (Python list) : {list_mixed}  → types: {[type(x).__name__ for x in list_mixed]}")
print(f"  arr_mixed   (NumPy array) : {arr_mixed}  → dtype: {arr_mixed.dtype}  (all cast to Unicode)")
print()
print(f"  list_nums   (Python list) : {list_nums}  → types: {[type(x).__name__ for x in list_nums]}")
print(f"  arr_nums    (NumPy array) : {arr_nums}  → dtype: {arr_nums.dtype}  (all cast to float64)")

  list_mixed  (Python list) : [1, 2, 'Denver']  → types: ['int', 'int', 'str']
  arr_mixed   (NumPy array) : ['1' '2' 'Denver']  → dtype: <U21  (all cast to Unicode)

  list_nums   (Python list) : [1, 2, 3.1]  → types: ['int', 'int', 'float']
  arr_nums    (NumPy array) : [1.  2.  3.1]  → dtype: float64  (all cast to float64)


---
<a id='2'></a>
## 2️⃣ Array Creation

You can create arrays from Python lists using `np.array()`.  
Arrays can be **1D** (a row), **2D** (a grid/matrix), or even higher dimensions.

In [6]:
# 1D Array — like a single row
arr_1d = np.array([10, 20, 30, 40, 50])

# 2D Array — like a table / matrix (rows × columns)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("  1D Array:", arr_1d)
print(f"Shape: {arr_1d.shape}")

print("\n  2D Array (2 rows × 3 cols):")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")


  1D Array: [10 20 30 40 50]
Shape: (5,)

  2D Array (2 rows × 3 cols):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


---
<a id='3'></a>
## 3️⃣ Array Generation Functions

Instead of typing values manually, NumPy lets you **generate** arrays automatically.

| Function | What it does |
|---|---|
| `np.arange(start, stop, step)` | Like Python `range()` but returns array |
| `np.zeros(shape)` | Array filled with 0s |
| `np.ones(shape)` | Array filled with 1s |
| `np.full(shape, value)` | Array filled with any value |
| `np.eye(n)` | Identity matrix (1s on diagonal) |
| `np.linspace(start, stop, n)` | n evenly-spaced values between start & stop |

In [8]:
arr_range  = np.arange(1, 11, 2)        # 1 to 10, step 2  → [1, 3, 5, 7, 9]
arr_zeros  = np.zeros(5)                # 5 zeros
arr_zeros2 = np.zeros((3, 2))           # 3×2 matrix of zeros
arr_ones   = np.ones((3, 2))            # 3×2 matrix of ones
arr_full   = np.full((2, 3), 7)         # 2×3 filled with 7
arr_eye    = np.eye(3)                  # 3×3 identity matrix
arr_lin    = np.linspace(1, 50, 5)      # 5 evenly spaced values from 1 to 50

print(f"  np.arange(1, 11, 2)    → {arr_range}")
print(f"  np.zeros(5)            → {arr_zeros}")
print(f"  np.linspace(1, 50, 5)  → {arr_lin}")
print(f"  np.full((2,3), 7)      →\n{arr_full}")
print(f"  np.eye(3) [Identity]   →\n{arr_eye}")
print(f"\n  np.zeros((3, 2)):\n{arr_zeros2}")
print(f"\n  np.ones((3, 2)):\n{arr_ones}")

  np.arange(1, 11, 2)    → [1 3 5 7 9]
  np.zeros(5)            → [0. 0. 0. 0. 0.]
  np.linspace(1, 50, 5)  → [ 1.   13.25 25.5  37.75 50.  ]
  np.full((2,3), 7)      →
[[7 7 7]
 [7 7 7]]
  np.eye(3) [Identity]   →
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

  np.zeros((3, 2)):
[[0. 0.]
 [0. 0.]
 [0. 0.]]

  np.ones((3, 2)):
[[1. 1.]
 [1. 1.]
 [1. 1.]]


---
<a id='4'></a>
## 4️⃣ Random Generation

NumPy's `random` module helps generate random data — useful in simulations, machine learning, and testing.

| Function | Output Range | Use Case |
|---|---|---|
| `np.random.rand(n)` | 0 to 1 (uniform) | Probabilities, normalization |
| `np.random.randn(n)` | ~−3 to 3 (normal/bell curve) | Standardization, ML |
| `np.random.randint(low, high, n)` | Integers in [low, high) | Dice rolls, sampling |
| `np.random.choice(arr, n)` | Elements from array | Random sampling |
| `np.random.seed(n)` | — | Makes random results reproducible |

In [9]:
np.random.seed(42)   # 🔑 Seed = same "random" results every run (great for learning!)

rand_uniform = np.random.rand(5)           # 5 floats between 0 and 1
rand_normal  = np.random.randn(5)          # 5 floats from standard normal distribution
rand_ints    = np.random.randint(1, 10, 4) # 4 random integers from 1 to 9
rand_single  = np.random.randint(5)        # One integer from 0 to 4
rand_choice  = np.random.choice(["red", "blue", "green", "yellow"], 3)  # Pick 3
rand_2d      = np.random.randint(1, 100, (3, 3))  # 3×3 matrix of random ints

print(f"  np.random.rand(5)             → {np.round(rand_uniform, 3)}")
print(f"    (uniform: values between 0 and 1)")
print()
print(f"  np.random.randn(5)            → {np.round(rand_normal, 3)}")
print(f"    (normal distribution: most values near 0)")
print()
print(f"  np.random.randint(1, 10, 4)   → {rand_ints}")
print(f"  np.random.randint(5)          → {rand_single}")
print()
print(f"  np.random.choice(colors, 3)   → {rand_choice}")
print(f"\n  Random 3×3 integer matrix:\n{rand_2d}")

  np.random.rand(5)             → [0.375 0.951 0.732 0.599 0.156]
    (uniform: values between 0 and 1)

  np.random.randn(5)            → [ 0.279  1.011 -0.581 -0.525 -0.571]
    (normal distribution: most values near 0)

  np.random.randint(1, 10, 4)   → [6 9 1 3]
  np.random.randint(5)          → 3

  np.random.choice(colors, 3)   → ['green' 'yellow' 'yellow']

  Random 3×3 integer matrix:
[[ 3 51  7]
 [21 73 39]
 [18  4 89]]


---
<a id='5'></a>
## 5️⃣ Array Attributes

Every NumPy array carries **metadata** about itself. These are called attributes.

| Attribute | Meaning |
|---|---|
| `.shape` | Dimensions as a tuple e.g. `(rows, cols)` |
| `.ndim` | Number of dimensions |
| `.size` | Total number of elements |
| `.dtype` | Data type of elements |
| `.itemsize` | Bytes used per element |
| `.nbytes` | Total bytes used by the array |

In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("  Array:")
print(arr)
print()
print(f"  .shape     → {arr.shape}       (2 rows, 3 columns)")
print(f"  .ndim      → {arr.ndim}            (2-dimensional)")
print(f"  .size      → {arr.size}            (total elements: 2×3=6)")
print(f"  .dtype     → {arr.dtype}        (64-bit integer)")
print(f"  .itemsize  → {arr.itemsize} bytes        (each int64 takes 8 bytes)")
print(f"  .nbytes    → {arr.nbytes} bytes       (total memory = size × itemsize)")

  Array:
[[1 2 3]
 [4 5 6]]

  .shape     → (2, 3)       (2 rows, 3 columns)
  .ndim      → 2            (2-dimensional)
  .size      → 6            (total elements: 2×3=6)
  .dtype     → int64        (64-bit integer)
  .itemsize  → 8 bytes        (each int64 takes 8 bytes)
  .nbytes    → 48 bytes       (total memory = size × itemsize)


---
<a id='6'></a>
## 6️⃣ Array Methods — Aggregations

These methods **summarize** the data in your array.

- `axis=0` → operate **column-by-column** (down the rows)
- `axis=1` → operate **row-by-row** (across the columns)

```
         axis=0 (↓)
       ┌───┬───┬───┐
axis=1 │ 1 │ 2 │ 3 │ →  row sum = 6
(→)    │ 4 │ 5 │ 6 │ →  row sum = 15
       └───┴───┴───┘
          ↓   ↓   ↓
col sum:  5   7   9
```

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("  Array:")
print(arr)
print()
print(f"  .min()          → {arr.min()}   (smallest element)")
print(f"  .max()          → {arr.max()}   (largest element)")
print(f"  .sum()          → {arr.sum()}  (total sum of all elements)")
print(f"  .mean()         → {arr.mean()}  (average of all elements)")
print()
print(f"  .argmin()       → {arr.argmin()}   (flat index of minimum value)")
print(f"  .argmax()       → {arr.argmax()}   (flat index of maximum value)")
print()
print(f"  np.sum(axis=0)  → {np.sum(arr, axis=0)}  (sum each COLUMN ↓)")
print(f"  np.sum(axis=1)  → {np.sum(arr, axis=1)}  (sum each ROW →)")
print()
print(f"  np.min(axis=0)  → {np.min(arr, axis=0)}  (min in each column)")
print(f"  np.max(axis=1)  → {np.max(arr, axis=1)}  (max in each row)")

  Array:
[[1 2 3]
 [4 5 6]]

  .min()          → 1   (smallest element)
  .max()          → 6   (largest element)
  .sum()          → 21  (total sum of all elements)
  .mean()         → 3.5  (average of all elements)

  .argmin()       → 0   (flat index of minimum value)
  .argmax()       → 5   (flat index of maximum value)

  np.sum(axis=0)  → [5 7 9]  (sum each COLUMN ↓)
  np.sum(axis=1)  → [ 6 15]  (sum each ROW →)

  np.min(axis=0)  → [1 2 3]  (min in each column)
  np.max(axis=1)  → [3 6]  (max in each row)


---
<a id='7'></a>
## 7️⃣ Reshaping & Resizing

You can **change the shape** of an array without changing its data.

- `reshape(rows, cols)` — returns a **new view** with the new shape (total elements must stay the same)
- `flatten()` — always returns a **copy** as 1D
- `ravel()` — returns a **view** as 1D (faster than flatten)
- `.T` — **transpose** (swap rows and columns)

In [21]:
arr = np.arange(1, 21)   # [1, 2, 3, ..., 20]
print("  Original (1D):", arr)
print(f"  shape: {arr.shape}")

arr_2d = arr.reshape(4, 5)
print("\n  Reshaped to (4×5):")
print(arr_2d)

arr_3d = arr.reshape(2, 2, 5)
print(f"\n  Reshaped to (2×2×5) — 3D array:")
print(arr_3d)

print(f"\n  .flatten() → {arr_2d.flatten()}  (always a copy)")
print(f"  .ravel()   → {arr_2d.ravel()}  (view if possible)")

# Transpose
small = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(f"\n  Original (2×3):\n{small}")
print(f"\n  .T — Transposed (3×2):\n{small.T}")

  Original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  shape: (20,)

  Reshaped to (4×5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

  Reshaped to (2×2×5) — 3D array:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]

  .flatten() → [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]  (always a copy)
  .ravel()   → [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]  (view if possible)

  Original (2×3):
[[1 2 3]
 [4 5 6]]

  .T — Transposed (3×2):
[[1 4]
 [2 5]
 [3 6]]


---
<a id='8'></a>
## 8️⃣ Mathematical Operations

NumPy operations are **vectorized** — they apply to every element at once with no loops needed.  
When arrays have different shapes, NumPy uses **broadcasting** to expand the smaller array.

In [22]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 2, 2, 2])   # Same shape
scalar = 2

print(f"  arr1         : {arr1}")
print(f"  arr2         : {arr2}")
print()
print(f"  Addition      arr1 + arr2  : {arr1 + arr2}  (same as np.add)")
print(f"  Subtraction   arr1 - arr2  : {arr1 - arr2}")
print(f"  Multiplication arr1 * arr2 : {arr1 * arr2}")
print(f"  Division      arr1 / arr2  : {arr1 / arr2}")
print(f"  Power         arr1 ** arr2 : {arr1 ** arr2}")
print(f"  Modulo        arr1 % arr2  : {arr1 % arr2}")
print()
print(f"  Broadcasting (arr1 + 10)   : {arr1 + 10}  ← scalar applied to every element")
print()
print(f"  np.sqrt(arr1)  : {np.round(np.sqrt(arr1), 4)}")
print(f"  np.abs([-3,-1, 2])  : {np.abs([-3, -1, 2])}")
print(f"  np.log([1, np.e, np.e**2])  : {np.round(np.log([1, np.e, np.e**2]), 3)}")

  arr1         : [1 2 3 4]
  arr2         : [2 2 2 2]

  Addition      arr1 + arr2  : [3 4 5 6]  (same as np.add)
  Subtraction   arr1 - arr2  : [-1  0  1  2]
  Multiplication arr1 * arr2 : [2 4 6 8]
  Division      arr1 / arr2  : [0.5 1.  1.5 2. ]
  Power         arr1 ** arr2 : [ 1  4  9 16]
  Modulo        arr1 % arr2  : [1 0 1 0]

  Broadcasting (arr1 + 10)   : [11 12 13 14]  ← scalar applied to every element

  np.sqrt(arr1)  : [1.     1.4142 1.7321 2.    ]
  np.abs([-3,-1, 2])  : [3 1 2]
  np.log([1, np.e, np.e**2])  : [0. 1. 2.]


---
<a id='9'></a>
## 9️⃣ Joining Arrays — Concatenate & Stack

| Function | What it does |
|---|---|
| `np.concatenate([a, b])` | Join along an existing axis |
| `np.hstack([a, b])` | Stack horizontally (side by side) |
| `np.vstack([a, b])` | Stack vertically (on top of each other) |
| `np.dstack([a, b])` | Stack along the depth (3rd axis) |

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"  a : {a}")
print(f"  b : {b}")
print()
print(f"  np.concatenate([a, b]) → {np.concatenate([a, b])}")
print(f"  np.hstack([a, b])      → {np.hstack([a, b])}  (same as concatenate for 1D)")
print(f"  np.vstack([a, b])      →\n{np.vstack([a, b])}  (stacks as rows)")

# 2D stacking
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print(f"\n  2D: m1:\n{m1}")
print(f"\n  2D: m2:\n{m2}")
print(f"\n  np.hstack([m1, m2]) — side by side:\n{np.hstack([m1, m2])}")
print(f"\n  np.vstack([m1, m2]) — on top:\n{np.vstack([m1, m2])}")

  a : [1 2 3 4]
  b : [5 6 7 8]

  np.concatenate([a, b]) → [1 2 3 4 5 6 7 8]
  np.hstack([a, b])      → [1 2 3 4 5 6 7 8]  (same as concatenate for 1D)
  np.vstack([a, b])      →
[[1 2 3 4]
 [5 6 7 8]]  (stacks as rows)

  2D: m1:
[[1 2]
 [3 4]]

  2D: m2:
[[5 6]
 [7 8]]

  np.hstack([m1, m2]) — side by side:
[[1 2 5 6]
 [3 4 7 8]]

  np.vstack([m1, m2]) — on top:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


---
<a id='10'></a>
## 🔟 Insert, Append & Delete

⚠️ **Important:** `np.append`, `np.insert`, and `np.delete` do **NOT** modify the original array.  
They always return a **new array**. You must save the result to a variable.

In [24]:
arr = np.array([10, 20, 30, 40])
print(f"  Original array : {arr}")
print()

# Append — adds value(s) at the END
appended = np.append(arr, [50, 60])
print(f"  np.append(arr, [50,60])        → {appended}")

# Insert — adds value at a specific INDEX
inserted = np.insert(arr, 2, 99)         # Insert 99 at index 2
print(f"  np.insert(arr, 2, 99)          → {inserted}  (99 inserted at index 2)")

# Insert multiple values at multiple positions
multi_insert = np.insert(arr, [1, 3], [15, 35])  # 15 before index 1, 35 before index 3
print(f"  np.insert(arr, [1,3], [15,35]) → {multi_insert}")

# Delete — removes element at index
deleted = np.delete(arr, 1)              # Delete element at index 1 (value=20)
print(f"  np.delete(arr, 1)              → {deleted}  (removed element at index 1)")
print(f"  Original unchanged             : {arr}  ← still the same!")

# Delete on 2D with axis
mat = np.arange(16).reshape(4, 4)
print(f"\n  4×4 matrix:\n{mat}")
print(f"\n  Delete row 0 (axis=0):\n{np.delete(mat, 0, axis=0)}")
print(f"\n  Delete col 0 (axis=1):\n{np.delete(mat, 0, axis=1)}")

  Original array : [10 20 30 40]

  np.append(arr, [50,60])        → [10 20 30 40 50 60]
  np.insert(arr, 2, 99)          → [10 20 99 30 40]  (99 inserted at index 2)
  np.insert(arr, [1,3], [15,35]) → [10 15 20 30 35 40]
  np.delete(arr, 1)              → [10 30 40]  (removed element at index 1)
  Original unchanged             : [10 20 30 40]  ← still the same!

  4×4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

  Delete row 0 (axis=0):
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

  Delete col 0 (axis=1):
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


---
<a id='11'></a>
## 1️⃣1️⃣ Splitting Arrays

The reverse of joining! Split one array into multiple smaller arrays.

| Function | What it does |
|---|---|
| `np.array_split(arr, n)` | Split into n parts (unequal OK) |
| `np.split(arr, n)` | Split into n equal parts (must divide evenly!) |
| `np.hsplit(arr, n)` | Split 2D array horizontally (by columns) |
| `np.vsplit(arr, n)` | Split 2D array vertically (by rows) |

In [25]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(f"  Original: {arr}")

parts = np.array_split(arr, 3)   # Split into 3 parts
print(f"\n  np.array_split(arr, 3):")
for i, p in enumerate(parts):
    print(f"    Part {i+1}: {p}")

# Unequal split (array_split is forgiving)
arr_odd = np.array([1, 2, 3, 4, 5])  # 5 elements split into 3 parts
unequal = np.array_split(arr_odd, 3)
print(f"\n  Unequal split [1,2,3,4,5] into 3:")
for i, p in enumerate(unequal):
    print(f"    Part {i+1}: {p}")

# 2D splitting
mat = np.arange(16).reshape(4, 4)
print(f"\n  4×4 matrix:\n{mat}")

h_parts = np.hsplit(mat, 2)   # Split into 2 halves along columns
print(f"\n  np.hsplit(mat, 2) — 2 column-halves:")
print(f"    Left half:\n{h_parts[0]}")
print(f"    Right half:\n{h_parts[1]}")

v_parts = np.vsplit(mat, 2)   # Split into 2 halves along rows
print(f"\n  np.vsplit(mat, 2) — 2 row-halves:")
print(f"    Top half:\n{v_parts[0]}")
print(f"    Bottom half:\n{v_parts[1]}")

  Original: [10 20 30 40 50 60]

  np.array_split(arr, 3):
    Part 1: [10 20]
    Part 2: [30 40]
    Part 3: [50 60]

  Unequal split [1,2,3,4,5] into 3:
    Part 1: [1 2]
    Part 2: [3 4]
    Part 3: [5]

  4×4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

  np.hsplit(mat, 2) — 2 column-halves:
    Left half:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
    Right half:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

  np.vsplit(mat, 2) — 2 row-halves:
    Top half:
[[0 1 2 3]
 [4 5 6 7]]
    Bottom half:
[[ 8  9 10 11]
 [12 13 14 15]]


---
<a id='12'></a>
## 1️⃣2️⃣ Searching in Arrays

Find elements, their positions, or filter arrays based on conditions.

In [26]:
a = np.arange(1, 21)   # [1, 2, ..., 20]
print(f"  Array a: {a}")

# np.where — find indices WHERE condition is True
idx = np.where(a == 3)
print(f"\n  np.where(a == 3)        → index {idx[0]}  (value 3 is at index {idx[0][0]})")

# np.where with replacement: where(condition, value_if_true, value_if_false)
replaced = np.where(a > 10, 1, 0)   # Replace >10 with 1, else 0
print(f"  np.where(a>10, 1, 0)    → {replaced}")

# Boolean indexing — fancy filtering
print(f"\n  a[a > 10]               → {a[a > 10]}  (only values > 10)")
print(f"  a[a % 2 == 0]           → {a[a % 2 == 0]}  (even numbers only)")

# np.searchsorted — find where to insert to keep sorted order
sorted_arr = np.array([10, 20, 30, 40, 50])
pos = np.searchsorted(sorted_arr, 25)
print(f"\n  sorted: {sorted_arr}")
print(f"  np.searchsorted(arr, 25) → index {pos}  (25 would fit at index {pos})")

  Array a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

  np.where(a == 3)        → index [2]  (value 3 is at index 2)
  np.where(a>10, 1, 0)    → [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]

  a[a > 10]               → [11 12 13 14 15 16 17 18 19 20]  (only values > 10)
  a[a % 2 == 0]           → [ 2  4  6  8 10 12 14 16 18 20]  (even numbers only)

  sorted: [10 20 30 40 50]
  np.searchsorted(arr, 25) → index 2  (25 would fit at index 2)


---
<a id='13'></a>
## 1️⃣3️⃣ Copying Arrays — Shallow vs Deep Copy

This is one of the most **common sources of bugs** for beginners! 🐛

| Operation | What happens |
|---|---|
| `b = a` | Both `a` and `b` point to the **same data** (no copy!) |
| `b = a.view()` | Shared data — shape can differ, but data is linked |
| `b = a.copy()` | **Independent copy** — changes to `b` don't affect `a` |

In [27]:
original = np.array([1, 2, 3, 4, 5])

# --- Assignment (NO copy) ---
ref = original       # Same memory!
ref[0] = 999
print("  ❌ Assignment (b = a) — NOT a copy:")
print(f"     After ref[0] = 999 → original: {original}  ← ALSO changed!")

# Reset
original = np.array([1, 2, 3, 4, 5])

# --- Deep Copy ---
deep = original.copy()   # Completely independent
deep[0] = 999
print("\n  ✅ Deep copy (b = a.copy()):")
print(f"     After deep[0] = 999 → original: {original}  ← unchanged!")
print(f"                         → deep    : {deep}  ← only deep changed")

# --- View (Shallow Copy) ---
original = np.array([1, 2, 3, 4, 5])
view = original.view()
view[0] = 777
print("\n  ⚠️  View (b = a.view()):")
print(f"     After view[0] = 777 → original: {original}  ← also changed (shared data)")

  ❌ Assignment (b = a) — NOT a copy:
     After ref[0] = 999 → original: [999   2   3   4   5]  ← ALSO changed!

  ✅ Deep copy (b = a.copy()):
     After deep[0] = 999 → original: [1 2 3 4 5]  ← unchanged!
                         → deep    : [999   2   3   4   5]  ← only deep changed

  ⚠️  View (b = a.view()):
     After view[0] = 777 → original: [777   2   3   4   5]  ← also changed (shared data)


---
<a id='14'></a>
## 1️⃣4️⃣ Statistical Functions

NumPy provides a full set of stats functions — great for data analysis!

| Function | Meaning |
|---|---|
| `np.mean` | Average |
| `np.median` | Middle value |
| `np.std` | Standard deviation (spread of data) |
| `np.var` | Variance (spread²) |
| `np.cumsum` | Running total |
| `np.cumprod` | Running product |
| `np.corrcoef` | Correlation matrix |

In [28]:
a = np.array([2, 4, 6, 8])
print(f"  Array: {a}")
print()
print(f"  np.mean(a)    → {np.mean(a)}    (average: sum/count = 20/4)")
print(f"  np.median(a)  → {np.median(a)}    (middle value of sorted array)")
print(f"  np.std(a)     → {np.std(a):.5f}  (how spread out values are)")
print(f"  np.var(a)     → {np.var(a)}    (standard deviation squared)")
print()
print(f"  np.cumsum(a)  → {np.cumsum(a)}   (running total: 2, 2+4, 2+4+6, ...)")
print(f"  np.cumprod(a) → {np.cumprod(a)}  (running product: 2, 2×4, 2×4×6, ...)")
print(f"  np.diff(a)    → {np.diff(a)}       (differences between consecutive elements)")

  Array: [2 4 6 8]

  np.mean(a)    → 5.0    (average: sum/count = 20/4)
  np.median(a)  → 5.0    (middle value of sorted array)
  np.std(a)     → 2.23607  (how spread out values are)
  np.var(a)     → 5.0    (standard deviation squared)

  np.cumsum(a)  → [ 2  6 12 20]   (running total: 2, 2+4, 2+4+6, ...)
  np.cumprod(a) → [  2   8  48 384]  (running product: 2, 2×4, 2×4×6, ...)
  np.diff(a)    → [2 2 2]       (differences between consecutive elements)


In [29]:
# Correlation measures the relationship between two variables (-1 to +1)
# +1 = perfect positive, -1 = perfect negative, ~0 = no relationship

price = np.array([100, 200, 250, 200])
sales = np.array([50,  25,  21,  25])

corr = np.corrcoef([price, sales])

print(f"  Price : {price}")
print(f"  Sales : {sales}")
print()
print("  Correlation matrix:")
print(np.round(corr, 3))
print()
print(f"  Correlation between price & sales: {corr[0, 1]:.3f}")
print("  → Strong NEGATIVE correlation: as price ↑, sales ↓  (makes intuitive sense!)")

  Price : [100 200 250 200]
  Sales : [50 25 21 25]

  Correlation matrix:
[[ 1.    -0.971]
 [-0.971  1.   ]]

  Correlation between price & sales: -0.971
  → Strong NEGATIVE correlation: as price ↑, sales ↓  (makes intuitive sense!)


---
<a id='15'></a>
## 1️⃣5️⃣ Matrix Operations

NumPy has powerful tools for linear algebra (matrices).

| Operation | Symbol / Function | Notes |
|---|---|---|
| Element-wise multiply | `a * b` | Each element × each element |
| Matrix multiply (dot product) | `np.dot(a, b)` or `a @ b` | Row × Column sums |
| Transpose | `a.T` | Flip rows and columns |
| Inverse | `np.linalg.inv(a)` | Only for square matrices |
| Determinant | `np.linalg.det(a)` | Scalar value of a matrix |

In [30]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print("  Matrix A:")
print(a)
print("\n  Matrix B:")
print(b)

print("\n  Element-wise multiply (a * b):")
print(a * b)
print("    (each element multiplied independently)")

print("\n  Matrix multiplication np.dot(a, b)  [or a @ b]:")
print(np.dot(a, b))
print("    (row × column sums — proper matrix multiplication)")

print("\n  Transpose a.T (flip rows ↔ cols):")
print(a.T)

print("\n  np.linalg.det(a) — Determinant:")
print(f"    {np.linalg.det(a):.1f}  (1×4 − 2×3 = −2)")

print("\n  np.linalg.inv(a) — Inverse of A:")
inv_a = np.linalg.inv(a)
print(inv_a)
print("\n  A × inv(A) should equal Identity:")
print(np.round(a @ inv_a, 10))  # Should be [[1,0],[0,1]]

  Matrix A:
[[1 2]
 [3 4]]

  Matrix B:
[[5 6]
 [7 8]]

  Element-wise multiply (a * b):
[[ 5 12]
 [21 32]]
    (each element multiplied independently)

  Matrix multiplication np.dot(a, b)  [or a @ b]:
[[19 22]
 [43 50]]
    (row × column sums — proper matrix multiplication)

  Transpose a.T (flip rows ↔ cols):
[[1 3]
 [2 4]]

  np.linalg.det(a) — Determinant:
    -2.0  (1×4 − 2×3 = −2)

  np.linalg.inv(a) — Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

  A × inv(A) should equal Identity:
[[1. 0.]
 [0. 1.]]
