In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
print(np.shape(arr))
# print(arr.shape)
print(np.size(arr))
# print(arr.size)
print(np.ndim(arr))
print(arr.dtype)
# print(type(arr))

(2, 3)
6
2
int32


Mathematical operations

In [4]:
arr1=np.array([1,2,3,4])
arr2=np.array([2])

In [5]:
print(np.add(arr1,arr2))
# print(arr1+arr2)
print(np.subtract(arr1,arr2))
# print(arr1-arr2)
print(np.multiply(arr1,arr2))
# print(arr1*arr2)
print(np.divide(arr1,arr2))
# print(arr1/arr2)
print(np.power(arr1,arr2))
print(np.sqrt(arr1))
print(np.concatenate([arr1,arr2]))      #,axis=1 for vertical concationation
print(np.hstack([arr1,arr2]))   #Horizontal concatination
print(arr1,arr2)
arr2=np.insert(arr2,[1,1,1],[4,5,6])
print(arr2)
print(np.vstack([arr1,arr2]))   #Vertical concatination

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4 2]
[1 2 3 4 2]
[1 2 3 4] [2]
[2 4 5 6]
[[1 2 3 4]
 [2 4 5 6]]


In [6]:
print(np.append(arr1,12))
print(np.array_split(arr1,2))
print(np.insert(arr1, 1, 14))


[ 1  2  3  4 12]
[array([1, 2]), array([3, 4])]
[ 1 14  2  3  4]


In [7]:
a=np.array([[1,2],[2,3]])
print("Normal insert\n",np.insert(a,1,[20,40]))
print("Insert with axis=0\n",np.insert(a,1,[20,40],axis=0))
print("Insert with axis=1\n",np.insert(a,1,[100,400], axis=1))

Normal insert
 [ 1 20 40  2  2  3]
Insert with axis=0
 [[ 1  2]
 [20 40]
 [ 2  3]]
Insert with axis=1
 [[  1 100   2]
 [  2 400   3]]


In [8]:
print(np.delete(a,0,axis=1))
print(np.delete(a,0,axis=0))
print(np.where(a==3))

[[2]
 [3]]
[[2 3]]
(array([1], dtype=int64), array([1], dtype=int64))


Stastistical Functions

In [9]:
print(a)
print(np.std(a))
print(np.var(a))
print(np.mean(a))
print(np.median(a))
print(np.cumsum(a))
print(np.cumprod(a))

[[1 2]
 [2 3]]
0.7071067811865476
0.5
2.0
2.0
[1 3 5 8]
[ 1  2  4 12]


In [10]:
price=[100,200,250,200]
sales=[50,25,21,25]
print(np.corrcoef([price,sales]))   #Finds correlation between data

[[ 1.         -0.97091858]
 [-0.97091858  1.        ]]
