In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
l=[1,2,3,4.1,"Denver"]
l

[1, 2, 3, 4.1, 'Denver']

In [6]:
np.array(l)   #As numpy array required single type of data and here we have different data types in list so it will auto convert into Unicode datatype

array(['1', '2', '3', '4.1', 'Denver'], dtype='<U32')

In [7]:
l=[[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.linspace(1,11,2)   #Generates specified numbers here 2 between 1 and 11

array([ 1., 11.])

In [17]:
np.random.rand(10)

array([0.32313498, 0.43916622, 0.69670924, 0.83719783, 0.4996624 ,
       0.6164581 , 0.26361914, 0.7259799 , 0.94699891, 0.37873675])

In [18]:
np.random.randint(10)   #gen num between 0 to 10

8

In [26]:
np.random.randint(10,20,5)    #gen 5 num between 10 and 20

array([12, 15, 13, 17, 12])

In [25]:
np.random.randn(10)   #Standardization (means gen num between -3 to 3)

array([-0.57806637,  0.68913208,  0.93278786, -0.29620841, -0.52844322,
       -0.8665834 ,  0.79131868,  1.23174752,  0.70494052, -1.81470022])

Array Attributes

In [38]:
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [39]:
arr.shape

(3, 3)

In [40]:
arr.size

9

In [41]:
arr.dtype

dtype('int64')

Array Methods

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(7)

In [44]:
arr.sum()

np.int64(36)

In [45]:
np.sum(arr,axis=0)    #return sum of column wise 1st col sum, 2nd col sum

array([ 9, 12, 15])

In [46]:
arr.mean()

np.float64(4.0)

In [47]:
arr.std()

np.float64(1.8257418583505538)

In [48]:
arr.argmax()

np.int64(8)

In [49]:
arr.argmin()

np.int64(0)

REshaping and Resizing


In [51]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])